### PR TITLE
Server-side Verification of documents

### LINKED ISSUE #315: Verification does not work without wallet
If I am logged in with Metamask, verification works fine. The same document inside of Incognito mode, without Metamask, does not get verified. However, if I enable the Metamask extension without logging in, the document gets verified. In other words: web3 support is required for verification - and this should be the content of the error message. Also the documentation does [not make this clear](https://github.com/ProxeusApp/community/blob/master/handbook/handbook.md#42-verification).

### Your environment

Chrome

### Steps to reproduce

Go through the complete workflow to produce a verifiable document. Verify it with and without Metamask.

### Expected behaviour

Proxeus tells me to have my wallet installed.

### Actual behaviour

I get an error saying the document cannot be verified (see screenshot)

Screenshot from 2023-06-26 13-47-59

### PR DESCRIPTION
**Pull request by tafonina**
should fix #315 
**New logic**
1. if user has metamask but the network is not the same as in the proxeus settings
   -> User should be prompt to change the metamask network ->
if user rejects to change network - the "Verify document" button should be disabled and error should be shown "Document can not be verified withing incorrect network"

2. If user doesn't have metamask - public RPC endpoint should be used
in case of any error using public RPC (for example "rate limit error") - user should see the error: "Please install metamask extension to verify document"

(Merge Spro changes to preprod branch)

### CODE REVIEW

File: ui/core/src/components/document/Verification.vue [hunk 1]
```diff
@@ -15,11 +15,16 @@
             </span>
         </p>
       </div>
-      <div class="stats col-sm-12 p-0" v-show="hasDocuments">
+      <div class="stats col-sm-12 p-0" v-show="hasDocuments && !hasPreinitError">
         <verification-file-entry :singleFile="files.length === 1" v-for="file in files" :key="file.name" :file="file"
                                  :wallet="wallet"
                                  :thumbnail="thumbnail"></verification-file-entry>
       </div>
+      <div class="stats col-sm-12 p-0" v-show="hasPreinitError">
```
Comment (loleg) [inline ui/core/src/components/document/Verification.vue:23]: Why are we using the same `verification-file-entry` component twice in a different way? Does it not always expect a `file` object? Perhaps we should have a separate component for showing network errors.

**Review by loleg — APPROVED** [review]

**Comment by loleg** [comment]
:heavy_check_mark:  Tested on preprod
